version: '3.8'

services:
  sd-ui:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: dev
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network: