version: '3.8'

services:
  sd-ui:
    build: .
    ports:
      - "3001:5173"
    environment:
      NODE_ENV: dev
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network: